const quiz = [
    {
        q:"다음 중 사진 속 가수가 부른 노래로 알맞은 것은?",
        image: './images/1.png',
        options:['구두', '결국 너잖아', '미워도 사랑하니까', '연애소설'],
        answer:'구두',
    },
    {
        q:'다음 뮤직비디오의 노래를 부른 아티스트는?',
        image: './images/2.png',
        options:['SISTAR', '서인국', 'K-WILL', '옴므'],
        answer:'K-WILL',
    },
    {
        q:'다음 사진 속 가수의 그룹 멤버는 총 인원은?',
        image: './images/3.png',
        options:['2', '8', '9', '11'],
        answer:'9',
    },
    {
        q:'다음 가사에 해당하는 가수는?',
        image: './images/4.png',
        options:['백지영', 'SG 워너비', 'V.O.S', '다비치'],
        answer:'다비치',
    },
    {
        q:'다음 앨범의 타이틀곡은?',
        image: './images/5.jpg',
        options:['첫사랑니', 'NUABO', 'Electric Shock', '피노키오'],
        answer:'Electric Shock',
    },
    {
        q:'다음 악보의 노래를 부른 가수는?',
        image: './images/6.jpg',
        options:['카라', '레이디스 코드', '나인뮤지스', '원더걸스'],
        answer:'원더걸스',
    },
    {
        q:'다음 사진 속 그룹이 부른 노래는?',
        image: './images/7.png',
        options:['밤하늘에', '너나 해', 'Loving U', '질투나요 Baby'],
        answer:'밤하늘에',
    },
    {
        q:'다음 안무사진에 맞는 노래는?',
        image: './images/8.png',
        options:['I want you back', 'Black or White', 'Mr. Mr.', '거울아 거울아'],
        answer:'Mr. Mr.',
    },
    {
        q:'다음 중 방송국별 연말 가요제 이름으로 알맞은 것은?',
        image: './images/9.png',
        options:['가요대전 SBS', '가요대제전 KBS', '가요 대축제 MBC', '마마 KM'],
        answer:'가요대전 SBS',
    },
    {
        q:'다음 중 사진 바로 뒤에 나올 가사로 알맞은 것은?',
        image: './images/10.jpg',
        options:['네게 좋은 남자가', '내가 미운가봐', '부처가 못 돼', '이젠 더 이상은'],
        answer:'부처가 못 돼',
    },
    {
        q:'다음 사진 속 인물로 올바른 것은?',
        image: './images/11.jpg',
        options:['이효리 - 비', '닉쿤 - 아이비', '택연 - 윤아', '트러블 메이커'],
        answer:'택연 - 윤아',
    },
    {
        q:'다음 OST곡의 드라마는?',
        image: './images/12.jpg',
        options:['베토벤 바이러스', '드림하이', '꽃보다 남자', '공부의 신'],
        answer:'꽃보다 남자',
    },
    {
        q:'다음 거울 모드 영상 속 아티스트의 노래 제목은?',
        image: './images/13.png',
        options:['상하이 로맨스', '아잉', '까탈레나', '립스틱 세우고'],
        answer:'까탈레나',
    },
    {
        q:'다음 UCC의 커버곡인 노래는?',
        image: './images/14.png',
        options:['동방신기 - 주문', 'SS501 - 파이터', '포미닛 - Hot Issue', '원더걸스 - Tell Me'],
        answer:'원더걸스 - Tell Me',
    },
    {
        q:'다음 사진 속 소속사의 가수가 부른 노래가 아닌 것은?',
        image: './images/15.jpg',
        options:['사.계.한', 'Shock', '한번 더 OK', '피노키오'],
        answer:'Shock',
    },
    {
        q:'다음 사진 속 음악 방송은?',
        image: './images/16.jpg',
        options:['Mnet', 'SBS', 'KBS', 'MBC'],
        answer:'MBC',
    },
    {
        q:'다음 사진 속 아티스트가 연습 중인 노래는?',
        image: './images/17.png',
        options:['그 남자는 반대', '내 여자 손대지마', '후유증', '10점 만점에 10점'],
        answer:'10점 만점에 10점',
    },
    {
        q:'다음 중 해당 가수와 콜라보한 적 없는 아이돌은?',
        image: './images/18.png',
        options:['다비치', '씨야', '초신성', '남녀공학'],
        answer:'남녀공학',
    },
    {
        q:'다음 가수의 데뷔곡은?',
        image: './images/19.png',
        options:['위아래', 'heart to heart', 'Whoz That Girl', '매일밤'],
        answer:'Whoz That Girl',
    },
    {
        q:'다음 사진과 가장 관련 깊은 가수는?',
        image: './images/20.jpg',
        options:['NS윤지', '인피니트', '써니힐', '비원에이포'],
        answer:'NS윤지',
    },

]
